<script lang="ts">
    export var funcionBotonOcultar: () => void;
</script>

<style>
@import url(https://db.onlinewebfonts.com/c/54bc695c63b2240b4798585129fe3112?family=F29LTZaridSlab-Regular);
.cuerpo{
    position: absolute;
    height: 500px;
    width: 100%;
    z-index: 1;
    left: 0;
    top: 0;
}
.cuadro{
    background-color:  #ffcdad;
    height: 98%;
    width: 50%;
    margin: auto;
    position: absolute;
    top: 100px;
    border: 2px solid #ff6300;
    border-radius: 30px;
    position: relative;
}
.boton{
    
    position:absolute;
    left: 4%;
    bottom: 4%; 
    height: 20%;
    width: 92%;
    border: 2px; 
    border-radius: 25px; 
    background-color: #b84900;
}
.sol { 
    position: absolute;
    top: 4%;
    left: 4%;
    width: 25%;
    max-height: 25%;
    height: 25%;  
}
.texto{
    position: absolute;
    top: -4%;
    left: 28%;
    right: 4%;
    font-size: 4vw;
    font-family: "F29LTZaridSlab-Regular";
    text-align: center;
    
}
.segun{
    position: absolute;
    top: 2%;
    left: 12%;
    width: 25%;
    height: 25%;
    color: white;
    font-family: "F29LTZaridSlab-Regular";
    font-size: 4vw;
}
.otro{
    position: absolute;
    top: 25%;
    left: 8%;
    width: 84%;
    height: 25%;
    color: black; 
    font-size: 2.4vw;
    text-align: center;
    font-family: "F29LTZaridSlab-Regular";
}

.otra{
    position: absolute;
    top: 40%;
    left: 8%;
    width: 84%;
    height: 25%;
    color: black; 
    font-size: 2.2vw;
    text-align: center;
    font-family: "F29LTZaridSlab-Regular";
}

.reto{
    position: absolute;
    top: 48%;
    left: 8%;
    width: 84%;
    height: 25%;
    color: black; 
    font-size: 2.2vw;
    text-align: center;
    font-family: "F29LTZaridSlab-Regular";
}

.casa{
    position: absolute;
    top: 65%;
    left: 8%;
    width: 84%;
    height: 25%;
    color: black; 
    font-size: 2.5vw;
    text-align: center;
    font-family: "F29LTZaridSlab-Regular";
}

.glasses{
    position: absolute;
    top: 55%;
    left: 40%;
    width: 20%;
    height: 20%;

}

.botonaso{
    position:absolute;
    border: 2px;
    border-radius: 25px;
    width: 100%;
    height: 100%;
    background-color: #ff6300;
    font-size: 5vw;
}
.fondo{
    position: absolute;
    width: 100%;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: grey;
    display:flex;
    z-index: 0;
}
</style>
<head>
    <link href="https://db.onlinewebfonts.com/c/54bc695c63b2240b4798585129fe3112?family=F29LTZaridSlab-Regular" rel="stylesheet">
    
</head>
<body>
    <div class="fondo">
    </div>
    <div class="cuerpo">
        <div class="cuadro">
            <div class="top">
            <!-- svelte-ignore a11y-missing-attribute -->
                
                <div class="dataop">
                    <img src="img/sun.png" class="sol">
                    <div>
                        <h1 class="segun">G4</h1>
                    </div>
                </div>
            </div>
            <h1 class="texto">Geomagnetic storm warning 
                type G4</h1>
            <p class="otro">The risks generated by G4 type storms are:
            </p>
            <li class="otra" type="disc">
                Systems: Possible widespread voltage control problems

            </li>
            <!-- <li class="reto" type="disc">
                HF Radio: Lost of radio contact for about an hour. 
            </li> -->
            <!-- <li class="casa" type="disc">
                Biologic: Passengers in high-flying may be exposed to radiation
            </li> -->
            <img class="glasses" src="img/electricity.png">
            <div class="boton">
                <button class="botonaso" on:click={funcionBotonOcultar}>
                    Understand
                </button>
            </div>
    
        </div>
    </div>
        
</body>